### ISSUE TITLE
Explorer not loading - going white screen

### ISSUE THREAD

**Issue by Severino** [harmony-one/explorer-v2-frontend#74] opened 2021-10-14 16:22 UTC
**What happens**
Sometimes when I check a wallet, it results in a white screen.

Following error is thrown:
![image](https://user-images.githubusercontent.com/7532600/137357296-6a82b228-3de5-49c9-9e00-651e7c5b66b6.png)

**How to reproduce**
This happens very inconsistently. The only idea I have is, that it's connected to heavily used wallets.
And some backend error occurs.

**Comment by drspinosa** [comment] 2021-12-13 10:34
I am having the same issue with my 2 wallets. I have tried 5 different browsers on 2 PCs and 2 browsers on an android mobile phone connected to mobile data and not the same network. I have done deep cache clean and the problem still persist 3 days now. I can though see other peoples wallets addresses on the explorer but not mine.

Any possible solutions ?

Thanks

**Comment by ArtemKolodko** [comment] 2022-01-18 21:36
Issue should be fixed with patch #100 
Was caused by exceeding localStorage size quota and unable to read tokens info

**Comment by givp** [comment] 2022-01-18 21:40
Already confirmed and merged. Closing.

**Closed by givp** 2022-01-18 21:40 UTC
