### ISSUE TITLE
TypeError: Cannot convert undefined to a BigInt

### ISSUE THREAD

**Issue by baakeydow** [harmony-one/explorer-v2-frontend#92] opened 2021-11-26 16:45 UTC
when hitting this url => https://explorer.pops.one/address/0xe399d7504310b84d38efd56cf8a29b38801d6449 you get `TypeError: Cannot convert undefined to a BigInt`

![Screenshot_2021-11-26_17-39-58](https://user-images.githubusercontent.com/16973742/143611105-2b805aa2-9018-4e88-8cca-1416bdeec782.png)

see https://github.com/harmony-one/explorer-v2-frontend/blob/master/src/components/ui/OneValueDropdown.tsx#L48

**Comment by baakeydow** [comment] 2021-11-27 10:07
at the time of writing this comment I cannot reproduce this issue, it seems like it's deeper than expected

**Comment by ArtemKolodko** [comment] 2022-01-19 13:42
Checked two cases:
- described above
- if client cannot get balances from node (bad connection, for example)

Cannot reproduce at this moment, closing issue

**Closed by ArtemKolodko** 2022-01-19 13:42 UTC
